### ISSUE TITLE
Не переводит на прошивке 2.18.15

### ISSUE THREAD

**Issue by negritos** [cakama3a/RUMIWIFI#6]
Добрый день! Обновил прошивку роутера Mi Mini до версии 2.18.15 и расширение перестало переводить абсолютно всё, из рабочего остался только чат. Можно как-то исправить эту проблему?

**Comment by cakama3a** [comment]
Вероятнее всего не срабатывает триггер активирующий перевод. Не распознает сайт так как у него изменилась структура. Мне нужна сохраненная браузером копия страницы роутера со всеми файлами и скриптами. Сделаю патч. Только сохранять нужно без плагина (все на китайском)

**Comment by AndreCrimea** [comment]
Уже давно стоит версия 2.18.15 и всё работает без проблем.
[[скриншот]](https://pp.userapi.com/c845419/v845419396/b0bc/5jGqktIK8GE.jpg)

**Comment by negritos** [comment]
@AndreCrimea попробовал на трёх разных браузерах Chrome (beta, dev, canary), на всех не переводит, есть только чат и надпись на русском "Пароль маршрутизатора"
![default](https://user-images.githubusercontent.com/37623544/37762866-8cf65118-2dce-11e8-8955-4cb13de19028.PNG)
![2](https://user-images.githubusercontent.com/37623544/37762867-8d158d3a-2dce-11e8-93df-12d7444e1778.PNG)

@cakama3a 
[copy.zip](https://github.com/cakama3a/RUMIWIFI/files/1836896/copy.zip)

**Comment by AndreCrimea** [comment]
@negritos может попробовать вручную удалить приложение и кэш?
У меня и в яндексе и в гугле стоит перевод. Яндекс правда пытается сам перевести))

**Comment by negritos** [comment]
@AndreCrimea не помогло к сожалению

**Comment by cakama3a** [comment]
ОС какая?

**Comment by negritos** [comment]
Win10

**Comment by cakama3a** [comment]
Должно работать. Если сохраненную копию страницы предоставите (китайской), посмотрю в чем дело.

**Comment by negritos** [comment]
@cakama3a я предоставил копию в 4 посте

**Comment by cakama3a** [comment]
Спасибо. Забавно но плагин который я загружаю из маркета не переводит, а тот что у меня в папке лежит на пк, работает на ура. Возможно дело в правах, может я в манифесте что-то не прописал. Они ведь идентичны. Ищем ответ.

**Comment by negritos** [comment]
И на всякий случай копия стартовой страницы (где пароль маршрутизатора)
[copy_start.zip](https://github.com/cakama3a/RUMIWIFI/files/1837432/copy_start.zip)

**Comment by cakama3a** [comment]
Сейчас я плагину добавил режим отладки. Удали его и установи снова версию 1.7.2
https://chrome.google.com/webstore/detail/rumiwifi/mbiehbednoakmhlmjcpgpciocekdjabp

Также покажи что напишет консоль
http://prntscr.com/iuv7x8

**Comment by negritos** [comment]
https://prnt.sc/iv7dvy

вхожу через 192.168.31.1

**Comment by cakama3a** [comment]
Так уже есть хорошие новости, скрипт запускается но до перевода дело не доходит. Сейчас сделаю еще пару манипуляций для более точных данных отладки. Напишу когда проверить.

**Comment by cakama3a** [comment]
Новая версия 1.7.31 доступна
https://chrome.google.com/webstore/detail/rumiwifi/mbiehbednoakmhlmjcpgpciocekdjabp
Баг не исправлен но лог должен выдать больше данных и думаю я уже знаю в чем проблема.

**Comment by negritos** [comment]
https://prnt.sc/iv9zzw

**Comment by cakama3a** [comment]
Версия Версия: 1.7.33 будет доступна через час. По идее все подчинил. Жду тестов.

**Comment by cakama3a** [comment]
Уже доступна, тестите

**Comment by negritos** [comment]
Ура! Всё работает, спасибо!
https://prnt.sc/ivb431

**Comment by cakama3a** [comment]
Надеюсь у остальных все тоже не сломалось =)

**Comment by cakama3a** [comment]
Проблема решена. Спасибо negritos
